### ISSUE TITLE
AppStart not possible

### ISSUE THREAD

**Issue by roest01** [section83/MacYTDL#10]
App is not signed with developer ID. Therefore getting (like) this screen:

![rtaImage](https://user-images.githubusercontent.com/2870718/64323501-ea1fc100-cfc4-11e9-96cc-bbc45b3e3cf2.png)

**Comment by section83** [comment]
Sorry but, _Tableau Desktop.pkg_ is not my app.  I can't tell from where it was downloaded but, not from here.  You should try to contact the software author: https://www.tableau.com/about/contact#contact_sales

It looks like they have a new version which I guess might be correctly signed.  The current download is called "TableauDesktop-2019-2-3.dmg".  Try that before complaining.

Cheers.

**Comment by roest01** [comment]
lol - just did that screenshot because my os is on german. -> getting (**like**) this screen...
Here you go:

![macytdl](https://user-images.githubusercontent.com/2870718/64332218-71c0fc00-cfd4-11e9-9a27-be9ebecfca4e.png)

**Comment by section83** [comment]
Many thanks for the dialog capture.  There is an issue with macOS 10.13, 10.14 and 10.15.  Apple has been gradually requiring apps to be code signed and notarised.  What messages you see varies with which version of macOS you are using.  MacYTDL is code signed.  But, it is not notarised.  To get MacYTDL working reliably in 10.15, I will have to get it notarised.

In the meantime, I suggest you make sure the Gatekeeper setting "Allow apps downloaded from:" is set to "App Store and identified developers".  Copy MacYTDL to the Applications folder.  Then, right-click (ie. control-click) MacYTDL and select "Open".  You should see this warning (or similar):

![Warning](https://user-images.githubusercontent.com/7471595/64395382-6554a600-d09d-11e9-82ea-cbc77c40cc00.png)

Click on "Open".  You might need to supply administrator credentials.  Then, it should start properly.

There's more info here: https://support.apple.com/en-us/HT202491
