### ISSUE TITLE
Unable to download this show

### ISSUE THREAD

**Issue by CdrSpock** [section83/MacYTDL#13]
Hello MACYTDL team.

First, thank you, thank you, thank you!!!
You provided me THE tool I needed.

Living in Europe, I was looking for a way to download shows from 7plus.com.au.
Of course I have to proceed through a VPN (NordVPN), it's slow but effective.

My problem:
I managed to download shows such as Coast Guard Florida (https://7plus.com.au/coast-guard-florida?episode-id=COGF01-001) or Outback Pilots (https://7plus.com.au/outback-pilots?episode-id=OBPI01-001), but I'm unable to download episodes from Air Rescue show (https://7plus.com.au/air-rescue?episode-id=AIRR-001). I have an error window
![Capture d’écran 2019-09-20 à 11 56 01](https://user-images.githubusercontent.com/55582156/65318321-b5ebf900-db9d-11e9-8503-36a08d491e65.png)

What am I doing that is not good?
Using MacYTDL version 1.10.1, on a 10.12.6 OS (iMac 27", mid 2011).

**Comment by section83** [comment]
I’m very glad MacYTDL works for you.  Just a few things:

*   That error message suggests the video is protected by Digital Rights Management (DRM).  7Plus randomly apply DRM to their videos. Sometimes even to just a few episodes of a series. They also change which videos have DRM so, it is worth while trying to download them again. For more information you could have a look at https://forums.whirlpool.net.au/thread/970lpxj3?p=27.

*   There is a bug in MacYTDL version 1.10.1 - the “Show settings before download” tick box on the main dialog causes a crash. However, It is safe to change that setting using the Settings function.

*   I will be releasing a new version in the next few days. Version 1.11 will have that bug fixed, a new “Check for MacYTDL updates” function and will remember the position on the screen. Most importantly, MacYTDL will be notarised by Apple which will make it safer.

*   MacYTDL runs under macOS 10.15 Catalina. Notarising the applet helps with that.

Sorry I can’t help more with the 7Plus problem.  MacYTDL uses the youtube-dl Python script to do the downloading. youtube-dl does not break DRM. There are a few tools out there which might be able to break the DRM including Firefox add-ins.

Cheers.


Garry

**Comment by section83** [comment]
MacYTDL is free but make a donation to the ytdl people

Garry Brooke

**Comment by section83** [comment]
Message sent in error.  Please disregard.


Garry Brooke
