### ISSUE TITLE
Send-URL-To-MacYTDL.workflow isn't compatible with Google Chrome

### ISSUE THREAD

**Issue by 11lucasarr11** [section83/MacYTDL#14]
Hi, very good work was yours on this app glad to be able to use it today.

I would like to sugest an improvement, adicionar this condition to the Send-URL-To-MacYTDL.workflow so that Google Chrome browser users can also use the service functionality :

"if app_name is "Chrome" then
    tell application "Google Chrome"
		set video_URL to get URL of active tab of first window
    end tell"

**Comment by section83** [comment]
Yes, I'll add this to the next release.  There is another improvement to the Service which will make it simpler (but not quicker).

Cheers.

**Comment by section83** [comment]
Fixed in v1.12
