### ISSUE TITLE
always auto re-start app itself even when be uninstalled

### ISSUE THREAD

**Issue by zronghui** [section83/MacYTDL#16]
is it a virus?

**Comment by section83** [comment]
This app cannot auto-start itself after being uninstalled.  The built in uninstaller moves ALL related files to the Trash. In the Trash, they cannot do anything.  Once Trash is emptied they are gone.

The main script and executables have been code signed and the applet has been notarized by Apple.  There is no virus code of any kind.  Except for the AtomicParsley and standard AppleScript executables, all code is open, accessible and can be checked by anyone.

Please add another comment if you have further questions.

Cheers.
