### ISSUE TITLE
Unable to install ffmpeg

### ISSUE THREAD

**Issue by andyrb412** [section83/MacYTDL#17]
Attempting to install latest version of MacYTDL, receiving the following error:

_error:  cannot open zipfile [ /Users/andy/Desktop//ffmpeg-4.2.2.zip ]
        Operation not permitted
unzip:  cannot find or open /Users/andy/Desktop//ffmpeg-4.2.2.zip, /Users/andy/Desktop//ffmpeg-4.2.2.zip.zip or /Users/andy/Desktop//ffmpeg-4.2.2.zip.ZIP._

Administrator access is granted during the install, but fails immediately afterwards.  Doesn't look like any files are being retrieved either.

**Comment by andyrb412** [comment]
I've installed ffmpeg manually and all is now ok, but MacYTDL itself continued to fail.

**Comment by section83** [comment]
Many thanks for reporting the bug.  Sorry for taking so long to respond.

Anyway, as you've seen, the path name to the FFmpeg zip file is incorrect: with two slashes.  Which version of macOS are you using ?  Catalina ?  I did test MacYTDL in Mojave and High Sierra and got no error despite the double slash.  I don't yet have a Catalina installation so, can't test it.

I've fixed the double-slash and after some more testing will release an update in a couple of days.

If you have MacYTDL working, go into _Settings_ and change your downloads folder to something else then back to what you want.  That should stop the error happening again.  If you can't run MacYTDL as yet:

- navigate to this file:   /Users/Andy/Preferences/MacYTDL/MacYTDL.plist.
- open that file in _TextEdit_ or your favourite text editor.
- look for the entry "DownloadFolder".
- change the line under that from "/Users/Andy/Desktop/"  to "/Users/Andy/Desktop". [i.e. delete the trailing slash].
- save and close.
- try MacYTDL again.

Let me know if you are still have troubles.

Cheers.

**Comment by section83** [comment]
I've tested _MacYTDL_ in a Catalina installation.  It installed all components and starts without error.  Anyway, the errant slash in the path to the _FFmpeg_ file will be fixed in v1.14.

I've also tested a few downloads and they nearly all worked.  There is a bug when downloading Youtube playlists that I've seen in Mojave so, it's not Catalina specific.

If you are still having problems please post here giving your macOS version.

Cheers.
