### ISSUE TITLE
Installer has still problems with ffmpeg download directory.

### ISSUE THREAD

**Issue by defcon5at** [section83/MacYTDL#18]
Maybe missing rights ? What is the default-directory MacYTDL checks if ffmpeg is installed so the user can install it manually ?

error:  cannot open zipfile [ /Users/dkasper/Desktop/ffmpeg-4.2.2.zip ]
        Operation not permitted
unzip:  cannot find or open /Users/xxxx/Desktop/ffmpeg-4.2.2.zip, /Users/dkasper/Desktop/ffmpeg-4.2.2.zip.zip or /Users/xxxx/Desktop/ffmpeg-4.2.2.zip.ZIP. (9)

MacOS Catalina.

**Comment by section83** [comment]
Many thanks for posting.

_FFmpeg_ is installed into: /usr/local/bin.  Full install instructions are on pages 4-6 of the Help file.

I'm stumped by this error at present.  I did a clean install of Catalina on a laptop a few days ago, downloaded and ran _MacYTDL_.  No error.  I've tested quite of lot of scenarios but still can't replicate the error.  There should be no permission problem with the destination folder as the _youtube-dl_ executable is installed before _FFmpeg_.  Nonetheless, I've read some cryptic comments about permission issues in Catalina which might be relevant.  Perhaps permission is needed in "Full Disk Access" – except my laptop doesn't have it and I get no errors.  I'll keep testing ideas on the cause.

Sorry for this.  But, if you can manually install _FFmpeg_ and _FFprobe_, you should be able to get _MacYTDL_ running.

Cheers.

**Comment by section83** [comment]
defcon5at,

It would help a lot if you can answer these questions:

- Did the ffmpeg-4.2.2.zip file finish downloading ?
- Was it left on your Desktop or was it deleted ?
- If you still have that file, what is its size ?
- Were you asked to provide admin credentials ?  If so, did you enter them correctly ?
- Is _youtube-dl_ installed into /usr/local/bin ?

It's possible that the download failed for some reason and left a corrupted zip file which unzip could not process.  I've found failed downloads a problem elsewhere including GitHub.  I'll look at adding a check on that to the FFmpeg download in case it helps.

Cheers.

**Comment by defcon5at** [comment]
> defcon5at,
> 
> It would help a lot if you can answer these questions:
> 
>     * Did the ffmpeg-4.2.2.zip file finish downloading ?

Yes.

>     * Was it left on your Desktop or was it deleted ?

The ZIPs were left on Desktop.

>     * If you still have that file, what is its size ?

22,6 and 22,7 MB

>     * Were you asked to provide admin credentials ?  If so, did you enter them correctly ?

Yes and yes.
 
>     * Is _youtube-dl_ installed into /usr/local/bin ?

Yes.

> 
> It's possible that the download failed for some reason and left a corrupted zip file which unzip could not process. I've found failed downloads a problem elsewhere including GitHub. I'll look at adding a check on that to the FFmpeg download in case it helps.
> 

The downloaded files worked fine with Keka so i don´t thing they are corrupted.

Cheers,
defcon5at

**Comment by section83** [comment]
Many thanks.  I was hoping it was a download issue.  Ah well, definitely more research needed.

Cheers.

**Comment by section83** [comment]
defcon5at,

Sorry to bother you again, but, before or after you got the "Operation not permitted" error, did you see a dialog like this one:
![catrev-security-warning-6c](https://user-images.githubusercontent.com/7471595/76051696-97e54a00-5fbf-11ea-8a76-8acba70e6095.jpg)

If so, did you click on "Don't Allow" ?

If so, can you open System Preferences; go to Security and Privacy; click on Privacy; select Files and Folders; and add MacYTDL ?

By the way, are you using macOS 10.15.3 ? i.e, the latest Catalina release ?

**Comment by defcon5at** [comment]
Hey, yes, i did see this dialog and permitted access. I´m using the german version of Cataline 10.15.3, so you will find "Schreibtisch" is allowed.

<img width="754" alt="Bildschirmfoto 2020-03-06 um 09 54 08" src="https://user-images.githubusercontent.com/61761702/76067974-994b4e00-5f90-11ea-95b6-786090e62634.png">

**Comment by section83** [comment]
Attempted fix: download FFmpeg-[version].zip to /usr/local/bin instead of downloads folder.  MacYTDL has already installed youtube-dl in that folder and so it must exist + not affected by Catalina file/folder permissions.

Fix to be in release v1.14.
