### ISSUE TITLE
Multilanguage GUI

### ISSUE THREAD

**Issue by bovirus** [section83/MacYTDL#19]
@section83 

Could be possible in future version have an external language file that enable translating in otehr languages?

Thanks.

**Comment by section83** [comment]
Yes, should be.  I'm trying to get localization to work in AppleScript.  Once that's done, I'll need help with translating text from English into other languages (I'm only monolingual).

**Comment by bovirus** [comment]
@section83 

I already translated YDL-UI (for Windows) in italian.
Then when will be ready post here a message for me and I will be happy to help you with Italian language.
Thanks.

**Comment by section83** [comment]
I'm now able to localize MacYTDL to a degree.  See the attached example:

![Italian](https://github.com/section83/MacYTDL/blob/master/images/Main%20Dialog%20-%20Italian.png?raw=true)

I'm having difficulty localising names of buttons in some dialogs.  It might take a while to solve that puzzle.

**Comment by bovirus** [comment]
@section83 

Thanks.

What's the file name that contains strings to translate/check?

**Comment by section83** [comment]
Sorry for taking so long. I've prepared a file which contains the English language text in MacYTDL. If you can still help, please type the Italian translations between the double quotes after the "=" sign.

[The English text file is in the "Code" folder.](https://github.com/section83/MacYTDL/blob/master/Code/English%20Text%20from%20MacYTDL.txt.zip)

In AppleScript, localisation is literally a lookup table.  To implement localisation in the code, I will have to add a new line of code and change another line, for every text item.  As you can see, there are a lot of text items so, it will take a while.

Anyway, any help will be great.  Cheers and take care.

**Comment by bovirus** [comment]
@scetion83

Thanks for the text to translate.
I will start soon.

Please avoid (if you can) use mix of strings to create a period.
The result can be different in different language. 

In long string like

"Atomic Parsley is installed.  When available, thumbnail images can now be embedded in your downloads.  Go to Settings to turn on that feature." = "";

Could be in multi-period string add a CR/LF?

In this string

"Code    Format" = "";

Are two terms or unique string (and in this case why so space characters)?
The teme os "code" or "Codec"?

**Comment by section83** [comment]
> Could be in multi-period string add a CR/LF?

Not sure what you mean.  Each string has to be discrete, ending in a LF.  But, I can split strings into separate sentences each of which is addressed by a variable.  It's extra work but doable. So, in the lookup table:

"Atomic Parsley is installed." = "[translation here]";
"When available, thumbnail images can now be embedded in your downloads." = "[translation here]";
"Go to Settings to turn on that feature." = "[translation here]";

My code can join them back together so the text can be shown in a dialog.  It'll be like this:

```
set the1stSentenceLabel to localized string "Atomic Parsley is installed."
set the2ndSentenceLabel to localized string "When available, thumbnail images can now be embedded in your downloads."
set the3rdSentenceLabel to localized string "Go to Settings to turn on that feature."

display dialog the1stSentenceLabel & " " & the2ndSentenceLabel & " " & the3rdSentenceLabel
with title diag_Title buttons {"OK"} default button {"OK"} with icon note giving up after 100
```

Would that be OK ?

By the way, it will help if the translation is not much longer than the English original.  Some of my dialogs are too narrow for long strings.  I used Google translate to try to get a German localisation.  Often, the German translation is significantly longer and doesn't fit in the dialog.

>"Code Format" = "";
>Are two terms or unique string (and in this case why so space characters)?
The teme os "code" or "Codec"?

The text between double quotes is just text, not code.  AppleScript uses a very simple lookup table.  My code supplies the English text – the command "localized string" means find that text in the lookup table and return the translation which is after the "=" sign.  The translated text returned goes into a variable which is used in the command which displays the dialog.  Each line in the lookup table must have the two text strings in plain double quotes separated by " = " and ending in ";" and a [Unix] line feed.


Many thanks.

**Comment by bovirus** [comment]
@section83

About long string like the exxmple the original output is

Atomic Parsley is installed. When available, thumbnail images can now be embedded in your downloads. Go to Settings to turn on that feature.

My request how to add in teh string CR/LçF to get an output like

Atomic Parsley is installed. 
When available, thumbnail images can now be embedded in your downloads. 
Go to Settings to turn on that feature.

about the string 

"Code   Format"

my request is why 4 spaces between two words
If it's a unique string you should have only one space

"Code Format"

Thanks.

**Comment by section83** [comment]
> "Code(one space)Format"

Of course, sorry I misunderstood.  You are correct – it's poor practice to position labels with spaces.  I did that because of how dialogs are created – UI elements are added sequentially from the bottom and cannot be positioned absolutely but are positioned relative to the preceding element.  Anyway, for now, please treat those as separate items:
```
"Code" = "";
"Format" = "";
```

> About long string like the example the original output is

My main concern is to provide meaning for users who don't understand very much.  Those sentences do have meaning together in context.  Nonetheless, I can separate those sentences in code if that ensures more accurate meaning in other languages.


Thank you – I hope you are not getting stir crazy.

**Comment by section83** [comment]
Version 1.15 of MacYTDL will be multilingual.  I'm also working on enabling language choice – so that users can decide when to use a language rather than be forced by their system settings.  Language choice probably will not be ready until v1.16.
