### ISSUE TITLE
Improvement - Italian language

### ISSUE THREAD

**Issue by bovirus** [section83/MacYTDL#21]
@section83 

Italian translation completed

[Italian Text from MacYTDL.zip](https://github.com/section83/MacYTDL/files/4781762/Italian.Text.from.MacYTDL.zip)

Please merge Thanks.

**Comment by section83** [comment]
Many thanks for these translations.  They have plugged in well.  There are a few entries which I forgot.  They are in the attached text file.  I have tried to do translations using Google Translate.  So, if you have time, can you check that they are correct ?

Thanks.
[Forgotten translations.txt](https://github.com/section83/MacYTDL/files/4791674/Forgotten.translations.txt)

**Comment by bovirus** [comment]
"Atomic Parsley installed:         Yes" = "Atomic Parsley installato:         Si";
"Clear" = "Azzera";
"Edit" = "Modifica";
"Edit settings" = "Modifica impostazioni";
"Embedded:" = "Incorporato";
"Install Atomic Parsley" = "Installa Atomic Parsley";
"Install Service" = "Installa servizio";
"is not valid. It should begin with the letters http. You need to paste a valid URL before selecting Download. Quit or OK to try again." = "non è valido. Dovrebbe iniziare con le lettere http. Devi incollare un URL valida prima di selezionare 'Download'. Esci o OK per riprovare.";
"Keep original file(s):" = "Mantieni file originali:";
"No subtitles" = "No sottotitoli";
"One-time settings:" = "Impostazioni singole:";
"Batches:" = "Batch";
"Paste URL here" = "Incolla qui l'URL";
"Remove last item"="Rimuovi ultimo elemento";
"Remux file format:" = "Formato file remux";
"Send E-Mail" = "Invia un'email";
"The URL" = "L'URL";
"Visit Site" = "Visita sito web";

"Clear" = "Azzera"; if it eman clear a list o cache etc
"Embedded:" = "Incorporato"; could be male or female (what's the refernce?)

"is not valid. It should begin with the letters http. You need to paste a valid URL before selecting Download. Quit or OK to try again." ;
Is not clear "Quit or OK to coninue" Quit is an option or other^

"Visit Site" coukld be "Visit Web Site"

**Comment by section83** [comment]
Again, many thanks.
Yes "Clear" means (a verb) to clear a list – in this case to remove URLs listed in the batch file.
"Embedded" can refer to subtitles or thumbnails.  In both, it means they are part of the data in the video file instead of a separate file. Once embedded, that data cannot be removed.
"Quit or OK to try again" are choices provided if user enters an invalid URL or nothing at all.  Quit means to quit MacYTDL OK means to display the Main dialog so user can enter the URL.
"Visit Site"=="Visit Web Site".

Cheers.

**Comment by bovirus** [comment]
@section83 

The grammar for Italian is more complex than English.

In Italian a term can be singular or plural and male or female and relative combination.

The term "Embedded" can have four translations depend by referring objects.
.

**Comment by section83** [comment]
Version 1.15.b.1 has been released. It has localisation implemented. Currently German and Italian are available. The nearly all the excellent Italian translations were provided by user [bovirus](https://github.com/bovirus). The German translations were done by the author using Google Translate and so are suspect.
