### ISSUE TITLE
Variable „theFFmpegInstallNotifyLabel“ not defined. (-2753)

### ISSUE THREAD

**Issue by MalEbenSo** [section83/MacYTDL#22]
Hi,
I am trying to run MacYTDL for the first time. I am now running into an error message (German language, as it is a German system):

> Die Variable „theFFmpegInstallNotifyLabel“ ist nicht definiert. (-2753)

This is with the latest version of MacYTDL. 
ytdl is installed via homebrew. 
macOS is Mojave 10.14.6

During installation I have declined all Macfeatures that can be enabled later on.

**Comment by section83** [comment]
MalEbenSo, many thanks.  I used the wrong variable in code which displays FFprobe install notification.

BTW, unless you have your own modifications, it might be easier to download latest YTDL directly or by using MacYTDL.

Cheers.
