### ISSUE TITLE
[Update youtube-dl source]

### ISSUE THREAD

**Issue by 1alessandro1** [section83/MacYTDL#23]
> MacYTDL would be useless without youtube-dl. It is a remarkable, feature rich utility maintained by the most dedicated group of volunteers.

Since the main repository has been taken down, I suggest to make the necessary changes to adapt the app

**Comment by section83** [comment]
Many thanks for the heads up. Existing copies of YTDL still work.  In the meantime I will have to consider what to do.

**Comment by section83** [comment]
youtube-dl has been restored to GitHub.
