### ISSUE TITLE
Improvement - Spanish language

### ISSUE THREAD

**Issue by michel-GH** [section83/MacYTDL#24]
Spanish translation ready, please just let me know if anything's missing.
[MacYTDL - spanish.txt](https://github.com/section83/MacYTDL/files/5615800/MacYTDL.-.spanish.txt)

**Comment by section83** [comment]
This is great, many thanks.  I'll add it to my work on version 1.16.  I'll pop back here if there I need any changes.

Cheers.

**Comment by section83** [comment]
I've reviewed the translations.  It's really close to final, many thanks.  I've attached a file with a few more lines that need to be translated.   If you can add those translations it will be finished.

Many thanks.
[Spanish - translations needed.txt](https://github.com/section83/MacYTDL/files/5640720/Spanish.-.translations.needed.txt)

**Comment by michel-GH** [comment]
Sure, here it is ;-)
[Spanish.-.translations.needed.txt](https://github.com/section83/MacYTDL/files/5641090/Spanish.-.translations.needed.txt)

I just want to point out that translations of single words or phrases without their context can lead to unintended errors. A good example could be "Progressing" in this txt. It could literally mean "Progressing" but also "Evolving", "Advancing", "Running", "Developing", etc and most probably "In progress" (this last one is the one I have chosen in the translation). Believe me that in Spanish it is not the same to say "Progresando" as "En curso" and that is difficult for a non-native to understand.

One option to solve this would be to get the dialog boxes captures in a file (I rule it out 'cause it is a huge job) and another one could be to improve the translation as those dialogs appear or know how to force them to appear.

**Comment by section83** [comment]
Michel, many thanks.

Yes, I have learned that translation is very sensitive to the context (e.g. German).  I am sure I've made mistakes so, I am hoping users expert in a language can tell me when there are errors.

I have screen captures of the most important dialogs, in English, in the Help file.  That will give a context in English.  It would not take very long to get captures of most dialogs in another language.  I can do a set in Spanish fairly soon if that will help.  Have attached a few I did during testing earlier this evening.

![Main dialog in Spanish](https://user-images.githubusercontent.com/7471595/101136733-df3d5b80-3661-11eb-9c58-f852cb7a119e.png)
![Settings - Text obscured by dropdown   small text box](https://user-images.githubusercontent.com/7471595/101136739-e1071f00-3661-11eb-9040-29e17e0a28cd.png)
![About dialog looks good](https://user-images.githubusercontent.com/7471595/101136740-e1071f00-3661-11eb-8229-630ecda90dd3.png)
![Utilities - blank  Start  button - not yet translated](https://user-images.githubusercontent.com/7471595/101136742-e19fb580-3661-11eb-8089-ac77d387a6aa.png)

**Comment by michel-GH** [comment]
Thanks Vincentius,

Going to the point:

![1](https://user-images.githubusercontent.com/75253508/101162053-18f66e00-3632-11eb-93de-c0ef866fc8c7.png)
![2](https://user-images.githubusercontent.com/75253508/101162091-2875b700-3632-11eb-8eb0-1a4599d01317.png)
![3](https://user-images.githubusercontent.com/75253508/101162109-2dd30180-3632-11eb-87d2-2ebdfef16731.png)
![4](https://user-images.githubusercontent.com/75253508/101162115-31668880-3632-11eb-9b24-3e75ee1f7206.png)

I hope it’s self explanatory, if not just let me know. In the concrete case of the word "version" the same word in Spanish needs an accent: "versi**ó**n".

BTW, if you also want to translate the months of the version please use the following list:
January = Enero
February = Febrero
March = Marzo
April = Abril
May = Mayo
June = Junio
July = Julio
August = Agosto
September = Septiembre
October = Octubre
November = Noviembre (capture example)
December = Diciembre

**Comment by section83** [comment]
Many thanks, this is a great help.  I'm sure that there will be small corrections and improvements over time.  Examples of new dialogs shown below.  Some responses to your suggestions:

- “Ajustes de una sola vez” seems to mean “One-time settings” which is correct – “Ajustes generales” seems to mean “General adjustments/settings” which is not correct in this context.

- “Credenciales para descargar” seems to mean “Credentials to download” which is close – the context is that some web sites require a login and password in order to download a video.  This one-time setting enables the user to supply those credentials which are passed to the web site by MacYTDL.  “Descargar credenciales” i.e. “Download credentials” seems too ambiguous.

- Similarly, “Subtítulos para esta descarga” seems to mean “Subtitles for this download” which is correct.

- Changing “best” to “mejor” in subtitles format will be difficult. The youtube-dl script uses the word “best” as an option.  Currently my code just takes the word “best” from the drop down box and sends that to youtube-dl.  I need to develop a way of translating from “mejor” back to “best” and the same translation in every other language.  Same issue with “Default” and “No remux”. I'll add this change to my list for version 1.17.

I’ve been able to quickly add code to use the translations for months.  Now I need months translated in German and Italian, which shouldn’t be too hard.

![Settings - Spanish](https://user-images.githubusercontent.com/7471595/101233870-1a499880-370f-11eb-9a55-32f0a55549ba.png)
![Utilities - Spanish](https://user-images.githubusercontent.com/7471595/101233872-1d448900-370f-11eb-8dd1-9dc66ee82e7c.png)
![Main - Spanish](https://user-images.githubusercontent.com/7471595/101233873-1ddd1f80-370f-11eb-9298-4a46af80e945.png)

**Comment by michel-GH** [comment]
Agree with the decisions you have made. Texts in the captures are coherent among them and that is the most important thing when someone tries to run software properly. Whatever you need, just let me know.

**Comment by section83** [comment]
Many thanks for the translations.  I had to do some more for the recent update. For those I used: https://www.spanishdict.com/translation.

Cheers

**Comment by michel-GH** [comment]
> Many thanks for the translations. I had to do some more for the recent update. For those I used: https://www.spanishdict.com/translation.
> 
> Cheers

May I suggest to use DeepL instead?

**Comment by section83** [comment]
Certainly. I’ll use DeepL for the next version.

Cheers.

**Comment by michel-GH** [comment]
> Certainly. I’ll use DeepL for the next version. Cheers.

In the meanwhile, here I am if you need me. And happy new year!

**Comment by section83** [comment]
Thanks and HNY back.  Hope you are surviving the virus etc.  Did it snow where you live ?

By the way, you can switch languages in MacYTDL without changing your system-wide language.  I've been crunching code for a while trying to add that feature when I found Apple already have it in macOS !  Such is life.

Go to System Preferences => Language & Region => Apps => click on "+" and add MacYTDL.

**Comment by michel-GH** [comment]
> Thanks and HNY back. Hope you are surviving the virus etc. Did it snow where you live ?

I live on the East coast of Spain, here the snow is a rarity although in January 2017 the sand dawned totally white... however in Madrid yesterday there was 80 cms of snow on some streets, something never seen before!

> By the way, you can switch languages in MacYTDL without changing your system-wide language. I've been crunching code for a while trying to add that feature when I found Apple already have it in macOS ! Such is life.
> Go to System Preferences => Language & Region => Apps => click on "+" and add MacYTDL.

Right but keep in mind that any application not in the default directory ( /Applications ) won't show on, as in my case since I have MacYTDL in the utilities directory.

**Comment by section83** [comment]
Yes, saw snow in Madrid on the local news.  We have had snow in Canberra quite often but, rarely more than 2-3cm – enough to dust the roofs.  The ranges to our west can have snow all winter which is a lovely view.

Enough off-topic.  People using macOS 10.14 and earlier are not able to control the language in individual apps. That might be reason to add it to MacYTDL.  However, I think that over time, people will upgrade to 10.15 and higher especially as Apple has ceased issuing security updates for 10.13 and earlier.  Some say 10.15 [is already over 65% of Mac users](https://gs.statcounter.com/macos-version-market-share/desktop/worldwide).  I doubt it's that much.  MacYTDL is getting rather large for an AppleScript applet and so, I'd rather put the time into functions directly related to downloading videos.

> keep in mind that any application not in the default directory ( /Applications ) won't show

See attached screen captures.  The language of apps stored outside /Applications can also be controlled.  I have MacYTDL in a development folder, for example.  It's not easy to see that there is an "Other..." option at the bottom of the list of apps.  That's the way to add apps which are not in /Applications.

![Other](https://user-images.githubusercontent.com/7471595/104137782-80eb6180-53f3-11eb-829d-2dd3237382d7.png)

Just for example, I've added Disk Utility and Migration Assistant which live in /Applications/Utilities:

![Added](https://user-images.githubusercontent.com/7471595/104137750-3f5ab680-53f3-11eb-8160-acb97d507b0d.png)

Anyway, hope all stays well for you.  Cheers.

**Comment by michel-GH** [comment]
I'm using 10.15.7.
Thanks for the "Other" option, I didn't notice it ;-)
![MacYTLD v1 15](https://user-images.githubusercontent.com/75253508/104167541-c9f3e380-53fc-11eb-825b-5ce8b368603a.png)
_MacYTLD v1.15 (inside Utilities folder: Shift-Command-U)_
