### ISSUE TITLE
Pagination of episode list

### ISSUE THREAD

**Issue by tom-parkinson** [section83/MacYTDL#26]
Just came across this tool and love it - thanks for putting it together! I tried to get an episode from a show with >100 episodes and wasn't able to move forward. See attached screenshot, or try `https://www.sbs.com.au/ondemand/program/mastermind`.

<img width="452" alt="Screen Shot 2021-02-25 at 9 59 01 AM" src="https://user-images.githubusercontent.com/40145982/109196357-72ad9680-7750-11eb-8a09-43034bf28b79.png">

It would be great if MacYTDL also allowed the use of a proxy. Is that in the pipeline?

**Comment by section83** [comment]
It's a bug.  I've been wondering what would happen with that many episodes – part of the issue is screen resolution which I can't fully test.  The dialog should show as many columns as needed to list all the episodes within the screen height.  You can use the "All episodes" function which should work - but will download all 174 episodes sequentially.  I'll try to fix this in the next release.

What is the screen resolution of your Mac ?

I haven't thought of adding a proxy setting so thanks for the question – it'll be in the next release too.  I've never used a proxy so, can you help with a few questions:

- youtube-dl supports http, https and socks schemes. Is that sufficient ?
- I'm thinking of error checking to ensure the URL starts with one of those three but, is that going to be a problem ?
- Should I check other aspects of the format of the URL entered ?
- Do you need the "--socket-timeout" setting ?

Many thanks.


Garry

**Comment by section83** [comment]
ALSO, you can still download one episode at a time by getting the URLs yourself.  To do that right click on the thumbnail image for the episode, choose "Copy Link", switch to MacYTDL and paste.

Cheers.

**Comment by tom-parkinson** [comment]
Thanks for the quick response. My screen resolution is 2880 x 1800. The bottom part of the dialog extends beyond the edge of the screen. So I guess the problem is the dialog sizing in both directions.

**Comment by tom-parkinson** [comment]
Proxy settings would be great! Then I'll be able to watch shows from home (like this one).
- http / https / socks is more than sufficient
- I generally use the IP address of the proxy server e.g. `https://torguard.net/network/socks5/`
- Mm I don't think so. One challenge is handling username and passwords. Most applications do so with the caveat that passwords are stored in plain-text in some config file on the local system.
- I don't think so. Others might, though.

**Comment by section83** [comment]
> Thanks for the quick response.

Easy, as my profile suggests, I'm retired and enjoy spending my daytime on the retirement project, MacYTDL.

> The bottom part of the dialog extends beyond the edge of the screen.

I can't see that from the capture you provided.  Can you send me a capture of the entire desktop ?  Send it to macytdl@gmail.com.

I think I have fixed the SBS dialog.  I had miscalculated the width needed for the dialog to show all the episodes.  I also had miscalculated the position of the heading.  Anyway, on my iMac @ 2560x1440 resolution, "Mastermind" looks like this:

![Screen Shot 2021-02-26 at 12 35 11 pm](https://user-images.githubusercontent.com/7471595/109242887-02764200-7830-11eb-9add-ac8b07b1a3b0.png)

> One challenge is handling username and passwords.

MacYTDL does have the "Credentials" option which might work – I've never been able to conclusively test it.

Cheers.

**Comment by section83** [comment]
Blast - there should be 5 columns of Mastermind episodes.  Back to debugging.

**Comment by tom-parkinson** [comment]
Screenshot as request:
<img width="1680" alt="Screen Shot 2021-02-26 at 10 26 01 AM" src="https://user-images.githubusercontent.com/40145982/109339859-1bc1c300-781d-11eb-9d71-ae692ebe1e3c.png">

**Comment by tom-parkinson** [comment]
> Blast - there should be 5 columns of Mastermind episodes. Back to debugging ....... Fixed:
> 
> ![SBS Chooser - fixed](https://user-images.githubusercontent.com/7471595/109260290-0024df80-7852-11eb-81bd-08012a8712b1.png)

Ayyy nice fix! I was interested in S03 which wasn't visible in the last version but clearly is on your latest dev version :-)

**Comment by tom-parkinson** [comment]
Happy to test the proxy implementation if needed

**Comment by section83** [comment]
Yes, please. That will be a great help as I have little experience with proxies.  Version 1.17 should be ready for testing in 1-2 days.

**Comment by section83** [comment]
I have opened a new issue for adding proxy settings – #27.

I've also uploaded an "Alpha Test" copy of MacYTDL with proxy settings added:

https://github.com/section83/MacYTDL/releases/download/1.17.b.1/MacYTDL.zip

I'll need your help to test this – I've tried using free proxies but I can't get any connections to work.

Cheers.
