### ISSUE TITLE
Add proxy settings for downloads

### ISSUE THREAD

**Issue by section83** [section83/MacYTDL#27]
MacYTDL should have an option for the user to supply a proxy server address so that downloads can be via that proxy. That option has been implemented in version 1.17.b.1 "alpha" test.

Version 1.17.b.1 is available here: https://github.com/section83/MacYTDL/releases/download/1.17.b.1/MacYTDL.zip

This copy has been code signed and notarised.

**Comment by tom-parkinson** [comment]
Works as expected using the format `socks5://username:password@ip.address:port`. Great work! Thanks for the effort to get this feature in there.

**Comment by section83** [comment]
Great.  I have been testing with free public proxies but none of them has worked.  So, I'm glad it does work after all.  There are more bugs in the alpha test version so, don't be surprised if there are crashes.  ABC are changing how they organise things on iView and it's breaking that part of MacYTDL every few days.

You should find that you can store a proxy URL but not use it – by turning off the checkbox.  But, you can't turn on the checkbox without providing a URL (which must start with http:, https or socks).

Cheers.
