### ISSUE TITLE
Error on initial run

### ISSUE THREAD

**Issue by ItsMorePaul** [section83/MacYTDL#39]
I'm getting an error on first run (and every time I reopen the app:)
Can’t get text 18 thru 29 of "". (-1728)

I'm using Public Beta 3 MacOS 12

**Comment by section83** [comment]
I can't tell from just that error exactly what the problem might be.  I suspect that something in Monterey has broken my code for getting the copyright data from the applet. My old iMac can't run Monterey (I had to patch it to run Catalina). So, I can't test MacYTDL in Monterey.  I'll need your help to solve the problem.

Can you try a few things for me ?

- Open _Script Editor_.
- Open MacYTDL in _Script Editor_.
- Show the bundle contents - which is the pane on the right hand side (by default it usually is already visible).
- Take a screen capture of the Bundle Info. It should look like this:

![Bundle Info](https://user-images.githubusercontent.com/7471595/126269361-ae66cb95-8226-47b5-a8cc-164c29b16081.png)

- Click on the "Play" button in the toolbar:

![Play](https://user-images.githubusercontent.com/7471595/126269524-09550c0d-38ed-4088-b428-a52c94607557.png)

If you get an error please do a screen capture and post back here.

Can you tell me whether any components have been installed ?  Check for these files:

- usr/local/bin/youtube-dl
- usr/local/bin/ffmpeg
- usr/local/bin/ffprobe
- Users/[your home]/Library/Preferences/MacYTDL/MacYTDL.plist

Lastly, can you tell me where you have saved the MacYTDL applet.  Is it in Applications or somewhere else ?

Many thanks for the report.


Garry

**Comment by section83** [comment]
This problem has not recurred in testing on macOS 10.13.6, 10.14 and 10.15.7.
