### ISSUE TITLE
[Bug] can't download using the batch method in the new versions....

### ISSUE THREAD

**Issue by zxzzz8** [section83/MacYTDL#45]
i just recently updated to version 1.19.1 [from.. v1.18b2 if im not mistaking....? maybe a version or 2 before that?]
and now i can't download the stuff i usually download from twitch using the batch function, as it gives me the error in the image i attached,
it seems to work fine tho if i try to download them individually not using the batch tool....

![Screen Shot 2021-11-27 at 13;45;27](https://user-images.githubusercontent.com/20977838/143805085-7fc1023d-ca1f-499e-adb3-b69313a799bc.png)

**Comment by section83** [comment]
Ouch.  Sorry.  That should not happen.  Can you send me a copy of the "BatchFile.txt" file by email or upload it here ?  It is located here:

>/Users/[your home]/Library/Preferences/BatchFile.txt

Thanks.

**Comment by zxzzz8** [comment]
oh i got used to editing BatchFile.txt directly, maybe with the new version it makes it differently, so it might be my bad? i completely forgot i edit it directly, sense there is that ''open file'' option, i treated it as the normal way to use it....

[BatchFile.txt](https://github.com/section83/MacYTDL/files/7616270/BatchFile.txt)

**Comment by zxzzz8** [comment]
ok i see.... never used the ''add a link to batch'', only the ''edit'' in the batch options,
i think it might had something to do with trouble adding multiple links simultaneously?

**Comment by zxzzz8** [comment]
tried to add it a single link at a time to the batch using the option in the main menu, it made this into the file:

https://www.twitch.tv/videos/1195942407#v1195942407 = 120211104-Date = Davidangel64 = 1636052414-UNIXtime =-=    It's cold outside. Nothing to do but play League! Let's go.    =-= 1080p60 - 1920x1080 (Source) .mp4
https://www.twitch.tv/videos/1199040314#v1199040314 = 120211107-Date = Davidangel64 = 1636316103-UNIXtime =-=    What if your boss was an orc IRL    =-= 1080p60 - 1920x1080 (Source) .mp4

however, when i tried to add multiple links [3 links] simultaneously:

![Screen Shot 2021-11-29 at 09;37;54](https://user-images.githubusercontent.com/20977838/143827564-2ef951de-9686-431d-adf1-347da0688e16.png)
.    =-= 1080p60 - 1920x1080 (Source) .mp4

**Comment by zxzzz8** [comment]
so is there currently no way anymore to add a list of links to the batch anywhere like i did before?
coz the way i did it before was by opening BatchFile.txt by either the ''edit'' in the batch options, or directly opening the file, and adding the list of links there....

**Comment by zxzzz8** [comment]
ok seems that i actually run into a different issue now, so adding a list of links works fine from the main menu,
its an issue with the original stream name of some of the streams that were named by the streamer....

the list of streams here:
https://blizzz.ovh/vod/#davidangel64?2021-01-01~2031-01-01

i guess its due to the stream name containing the " unicode? but before that it worked just fine by removing the digits it couldn't handle....

**Comment by zxzzz8** [comment]
btw i understand in the new version, the naming format can handle folders?
i think i saw that in the update notes....

my current naming format is:
%(id)s = 1%(upload_date)s-Date = %(uploader)s = %(timestamp)s-UNIXtime =-=    %(fulltitle)s    =-= %(format)s .%(ext)s

so do i just add a / to it to make the folder? like:
%(id)s/1%(upload_date)s-Date = %(uploader)s = %(timestamp)s-UNIXtime =-=    %(fulltitle)s    =-= %(format)s .%(ext)s

and then it will make a folder w the naming of %(id)s and the inside files with the name 
1%(upload_date)s-Date = %(uploader)s = %(timestamp)s-UNIXtime =-=    %(fulltitle)s    =-= %(format)s .%(ext)s

did i understand it correctly?

**Comment by zxzzz8** [comment]
ok so to summarize about the issue that is left here: 
so trying to download this file as is:
https://www.twitch.tv/videos/1200659657
works fine, but i can't add it to the batch file due to that issue with that second error message image i gave earlier....

**Comment by zxzzz8** [comment]
btw im noticing its quite an issue to add links one after the other to the main menu, as i can't click 'enter' to move to a new line for a new link, because it try to register it as choosing the 'continue', and it seems it does issues when its just a space between the links? so ill always need to prepare it in advance in a txt before copy to the menu? its not a big deal but i feel that it might be a bit poor design?

i think thats the main reason i didn't add links to the batch from the main menu in the past....

**Comment by zxzzz8** [comment]
![Screen Shot 2021-11-29 at 11;09;30](https://user-images.githubusercontent.com/20977838/143839391-937f1ae6-2c8b-4a57-b413-96ea7a684852.png)

ok this happen either way, so its not related to the file name then? 
could it be that im not suppose to add a list of links to the batch at once to begin with? im starting to think thats what i did wrong....? 
tho if thats really the case, considering it takes a while to add the links one by one, then i guess my next feature request is add a list of links to the batch simultaneously, as it seems like such a natural thing, maybe i got used to that convenience from just pasting them to BatchFile.txt directly in the older versions....

**Comment by section83** [comment]
My bad and it's a whopper.  I forgot to update the Help file with detail on the format of the BatchFile.txt file. Each line now contains the file name as well as the URL. I also forgot to deal with the facility for users to edit the file themselves.  Lastly, the download batch function crashes.  So, the batch function is dead for now.  Maybe I forgot to test it.


In the meantime, FWIW I've uploaded a copy of your BatchFile.txt file which is now correctly formatted.
[BatchFile.txt](https://github.com/section83/MacYTDL/files/7617253/BatchFile.txt)

I created that using the "Add URL to Batch" function but I had to edit out some extraneous "#" symbols.  So, there 's a bug in the "Add URL to Batch" code too.


>so is there currently no way anymore to add a list of links to the batch anywhere like i did before?

Thing is, when it works properly, the "Add URL to Batch" function does a simulate to ensure the download will work and to get the file name.  You can override that by manually editing the file but, if you don't get the file name right, the "Play" function available when download is finished will not work.  Not a big issue.


>so do i just add a / to it to make the folder? like:
%(id)s/1%(upload_date)s-Date = %(uploader)s = %(timestamp)s-UNIXtime =-= %(fulltitle)s =-= %(format)s .%(ext)s

That should work but I think "-UNIXtime" will be treated as a literal.  The folder(s) created will be inside your downloads folder.  It's quite complicated so, I'll have to test it to see what happens.


>btw im noticing its quite an issue to add links one after the other to the main menu, as i can't click 'enter' to move to a new line for a new link, because it try to register it as choosing the 'continue', and it seems it does issues when its just a space between the links? so ill always need to prepare it in advance in a txt before copy to the menu? its not a big deal but i feel that it might be a bit poor design?

You can download a number of videos in one process by entering them in the text box labelled "Paste URL here". Only **put a single space** between each URL. Returns/LineFeeds will give it conniptions.  Similarly, you can add a number of URLs to the batch file in one step by entering them with a space between each one. A little more detail on p.8 of the Help.

But, the batch download function is broken for the time being. So, just download directly.

Again, my apologies for the mess. Version 1.19.2 should fix these issues.  I'll start working on it tomorrow.

Cheers.

**Comment by section83** [comment]
Hopefully, this is fixed in version 1.19.2. There were actually a number of different bugs in the batch processing which seems to work now.

Also, I've added a crude check to ensure the batch file is in the correct format. If format is wrong, it tells user to read the Help file.

Also, also, the upper limit on file names is 255 characters.  I've added a check which removes the custom template if it causes the file name to be too long.  I can't think of another circumstance in which the file name will be too long – well, I haven't seen one yet.  Option of abbreviating date-time stamp and/or standard file name text would not be enough in some situations.

**Comment by zxzzz8** [comment]
you mean if the costume template gives a filename with over 255, it will not use it without warning the user or anything? coz i never want it to do that, if the name is too long, then either don't download the file with an error in the log, or just cut from the end the result of the template name to a length of 255, which tbh would be the most reasonable, standard and elegant solution i believe....
i mean, some of the data in the name template, i have no other way to get, so i don't want to let it proceed with the download if it doesn't save it....

**Comment by section83** [comment]
macOS cannot store files with names longer than 255 characters.  If that becomes likely, MacYTDL will pop this warning (logo will replace the red bug):



So, you will have the option of reducing the length of the custom template.  It’s crude and I might be able to improve it in the future.  Still, it’s better than a crash.  Because of all the bugs, I’m trying to get version 1.19.2 out as soon as I can.  I have had technical problems e.g. I can’t test a signed-notarised copy of MacYTDL on my iMac.  macOS refuses to let it run.

Cheers.


Garry
