### ISSUE TITLE
Error in reading response file: 

### ISSUE THREAD

**Issue by Nellio** [section83/MacYTDL#49]
macOS 12.1 Monterey
M1 processor
MacYTDL, version 1.19.1, set to install and use YTDLP

<img width="592" alt="Capture d’écran 2021-12-17 à 09 57 23" src="https://user-images.githubusercontent.com/2989326/146518586-54932866-ddd4-446d-94be-2d3969a282a7.png">

A few seconds after clicking the “Continue” button, the following error message pops up, warning of an “eof” error:

<img width="532" alt="Capture d’écran 2021-12-17 à 09 58 12" src="https://user-images.githubusercontent.com/2989326/146518598-f520dfbd-e9ad-488e-9ee5-2a1f04cd27a2.png">

Clicking “OK” lets the download continue silently (no progress window is displayed) and complete successfully.

Not clicking “OK” leads after a few seconds to a download error notification, and a “.part” download file in the MacYTDL download folder.

**Comment by section83** [comment]
Many thanks for making the report.  Sorry, MacYTDL is not working properly.  Yours is the first report I've received of someone using an M1 Mac with macOS Monterey.

Did you get this warning ?


![Warning](https://user-images.githubusercontent.com/7471595/146617586-b9393258-6ae1-4a09-be85-9bf738f346c0.png)

Did it download 9 videos ?

Did you see this ?

![Did you see this ?](https://user-images.githubusercontent.com/7471595/146617841-5a904c7a-d01b-44ae-a435-1224e1dd4d25.png)

This might be a kind of YouTube video URL that I've not seen before.  I need to do some research.

Thanks again.

**Comment by Nellio** [comment]
1. No such warning.
2. No. As I didn’t click OK, the download aborted silently and left a .part file of the individual video, with the correct individual video file name, in the download folder. [Pourquoi la moto diesel n'a JAMAIS marché .f401.mp4.part]
3. No. 
You’re welcome. :)

**Comment by Nellio** [comment]
I just saw you made a typo in the URL you tested: 'wqtch' instead of ‘watch’. The correct URL is: https://www.youtube.com/watch?v=sZC-fh8UJZA

**Comment by section83** [comment]
That's embarrassing ! Anyway, it has alerted me to the issue of YT channels.

With the correct URL I get a normal progress monitor and a complete download:

![Progress](https://user-images.githubusercontent.com/7471595/146636882-cb3924c4-eead-4eac-a997-139b3baeeab3.png)

Is this the page from which you are downloading ?

![Page](https://user-images.githubusercontent.com/7471595/146636858-00d122b8-b3d7-4f89-8bff-69fd0441517c.jpg)

I get a normal "response" file and a normal advice that download has completed.
![Finished](https://user-images.githubusercontent.com/7471595/146637113-cd87d8ce-4339-4276-bff1-530d1b96edac.png)

Can you send me the "response file (if there is one) ?  If it contains any personal information (e.g. name of your home folder), send it by email to macytdl@gmail.com.

It is located in:

/Users/[Your home folder]/Library/Preferences/MacYTDL/

Its name will be like this:

youtube-dl_response-Pourquoi_la_moto_diesel_n'a_JAMAIS_marché_.-Saturday_18_December_2021_at_8_33_05_pm.txt

Also, can you send a copy of the simulate file: "youtube-dl_simulate.txt" and "MacYTDL.plist" that are in the same folder.

Thanks.

**Comment by section83** [comment]
And yet another question: Are you using youtube-dl ?  If so, switch to YT-DLP and try again.

youtube-dl does work on my Mac but, the download is very slow.

**Comment by Nellio** [comment]
1. Yes.

2. "MacYTDL, version 1.19.1, set to install and use YTDLP"

What’s strange is that when I click OK in the error dialog window, the download procedes silently and completes successfully.

**Comment by section83** [comment]
OK, I think I found the problem. My code in the "Monitor" was relying on the text of an error message to control formation of the dialog. I assumed the message would be in English. That was incorrect. So, I've used a different method.

I can't test this so, I hope you can give it a try:

https://github.com/section83/MacYTDL/releases/download/1.19.3/MacYTDL-v1.19.3.dmg

**Comment by Nellio** [comment]
Works like a charm. Thanks!
