### ISSUE TITLE
MacYTDL Batch Functions: "The command exited with a non-zero status. (1)"

### ISSUE THREAD

**Issue by jeremydouglass** [section83/MacYTDL#54]
I'm using MacYTDL 1.21, 27 March 2022, newly installed on MacOS 12.2.1 (M1 Pro).

Problem: batch functions "Download" button causes MacYTDL to crash with the error "The command exited with a non-zero status. (1)"

Steps to reproduce:

1. Open MacYTDL
2. Check "Add to Batch"
3. Input a URL and click Continue
4. Check "Open Batch functions"
5. (Optionally, confirm with Edit that batch file contains a valid url, #, and valid target file name with no special characters, and a single line final line break)
6. Click "Download"

MacYTDL crashes with the error "The command exited with a non-zero status. (1)"

I've tried different URLs and different settings, but nothing seems to avoid the crash. One-at-a-time downloading outside batch mode is working just fine.

> Note: Running the Batch functions "Download" when the list is completely empty causes a different crash -- "A resource wasn’t found. (-192)" -- and crashing there is also not desirable, but it isn't unexpected that you can't run a batch on nothing.

**Comment by section83** [comment]
Jeremy, thank you for making contact.

Sorry about the bugs.  I'll work on them later today.

Last time I tested the download batch function, it popped a message saying batch file is empty, which is what it should do.  I don't know yet why it no longer works.

I'll post here when I have news.

**Comment by section83** [comment]
The crash on using batch download was an oversight by me.  I've decided to release a quick version 1.21.1 tomorrow (Canberra time) as there are a few bug fixes that should be released.

The "resource not found" error caused when batch file empty refers to the file containing the MacYTDL logo – I made a muck of referring macOS to the path name. The fix will be in v1.21.1.

Many thanks.

**Comment by jeremydouglass** [comment]
Thanks so much, and let me know if I can help with testing in any way.

**Comment by section83** [comment]
Thanks for the offer. I'm working through personal matters so, will delay release for a few days. Might release as beta.

Cheers.
