### ISSUE TITLE
Is there anyone could provide a download link of both libcrypto.44.dylib and libssl.46.dylib?

### ISSUE THREAD

**Issue by QAQDE** [section83/MacYTDL#56]
Hi, I am currently using Mojave on my iMac. Due of my profession, I cannot upgrade to catalina. Sadly I could not find any download links on google providing libcrypto.44.dylib and libssl.46.dylib, which is the essential parts for using yt-dlp service in Mojave machine. I do not have a second Mac for me to copy those libraries into my Mojave. Is there any nice guy to provide yours and share it to this project?  Many thanks.     These two dylib are located in  “/usr/local/lib/” 

Best

**Comment by section83** [comment]
QAQDE, please email me at macytdl@gmail.com. We can organise something privately.
