### ISSUE TITLE
Error when downloading playlist

### ISSUE THREAD

**Issue by frissonlabs** [section83/MacYTDL#62]
Tried to download a playlist and getting the error shown in the attached screenshot.

<img width="262" alt="Screenshot 2023-01-14 at 3 06 35 AM" src="https://user-images.githubusercontent.com/2988351/212469111-7116095a-e44a-4537-98ab-2117f277ad97.png">

**Comment by section83** [comment]
Thank you for posting the issue.  I'm sorry you got the error.  I need more detail so I can diagnose the problem.

Can you provide the URL from which you were trying to download ?

Can you describe when you got the error ? For example, did the "Monitor" dialog show ?

Can you send by email to me a copy of your MacYTDL preferences file ?  It this file:

> [Your Mac]/Users/[Your home]/Library/Preferences/MacYTDL/MacYTDL.plist.

To send me an email: open MacYTDL; click on "Utilities"; click on "About MacYTDL"; click on "Send E-Mail".  That will open a blank message in your default email app.  Attach a copy of the MacYTDL.plist file and send.

By the way, you can screen capture a dialog precisely by pressing command-shift-4; space bar; place cursor over dialog; click mouse button.

**Comment by frissonlabs** [comment]
No worries.

I used this URL: 
https://music.youtube.com/playlist?list=OLAK5uy_kUzk7J2o-S6oCKaKit5ZY3FTb5OqjAyys

I got it right after pressing "Continue" from the main screen.
<img width="482" alt="Screenshot 2023-01-14 at 10 58 37 PM" src="https://user-images.githubusercontent.com/2988351/212527556-a1bc0a58-65d3-4b8e-9362-1d28fde3eded.png">

 It actually hangs on that screen for several seconds before the following progress dialog pops up. Not sure if that's normal.
<img width="353" alt="Screenshot 2023-01-14 at 11 00 47 PM" src="https://user-images.githubusercontent.com/2988351/212527586-81c8dfc5-06b7-4686-b014-66ea08d91562.png">

I get the original error popup right after (or, rather, alongside) that.

Just sent the .plist file as well.

**Comment by section83** [comment]
Thank you for all that.  It helps narrow down where the bug is located.

That "progress" dialog is just a notification that the playlist is being checked.  I added that a while back because checking playlists takes a long time.

It looks like I have a bug in the code which handles the result of that checking.  It will take a day or two to figure it out.

Cheers.

**Comment by section83** [comment]
I've found the problem.  It's affecting all playlists. A fix will be in v1.23 out, hopefully, later this month.

Many thanks.

**Comment by Raymond-Adams** [comment]
I have the same issue, except MacYTDL crashes when I click "OK" and the progress dialog does not pop up.

The error occurred after pasting https://www.youtube.com/watch?v=NNnIGh9g6fA&list=PL848F2368C90DDC3D and pressing "Continue".



<img width="372" alt="MacYTDL_Playlist_Error" src="https://user-images.githubusercontent.com/102918860/213048988-679a4c3b-d8f5-4908-9466-7387418b05a0.png">

**Comment by section83** [comment]
[Raymond-Adams](https://github.com/Raymond-Adams)

Thanks for making contact.  Apologies.  There is a bug in my code which works out how many items are in a playlist.  I have fixed the code and it will be in the next release of MAcYTDL.  Given how critical playlists can be, I'll try to release the next version, v1.23, by next Monday (Sydney time).

**Comment by section83** [comment]
I think version 1.23 fixes this playlist bug.

**Comment by Raymond-Adams** [comment]
I downloaded the full playlist successfully. Thank you!

**Comment by section83** [comment]
Phew !  Many thanks for letting me know.
