### ISSUE TITLE
Batch downloading not working (The variable YTDL_QT_Compat is not defined.)

### ISSUE THREAD

**Issue by kuglee** [section83/MacYTDL#63]
Hi,

Thank for the app. It was working great before I updated to the latest version. Now I get the following error if I want to use the bach downloading feature:

<img width="260" alt="yt" src="https://user-images.githubusercontent.com/1316211/216991353-6a7df3f3-3eff-46f0-8554-00a94e391970.png">

**Comment by section83** [comment]
[kuglee](https://github.com/kuglee)

Many thanks for posting this issue.  It's a bug.  As batch downloads don't work, and there are other bugs, I hope to release a fix by Friday, 10 February or Saturday, 11 February.  It will be version 1.23.1.

There is no direct workaround. However, you can use Terminal to do a download from your current batch file:

- Open _Terminal_ (located in [Your Mac/Applications/Utilities).
- Type this:

yt-dlp --ignore-errors --newline --verbose  -o '\\''%(title)s.%(ext)s'\\''  --batch-file '/Users/[Your Home]/Library/Preferences/MacYTDL/BatchFile.txt'

Thanks again.

**Comment by kuglee** [comment]
Thanks.

**Comment by section83** [comment]
UPDATE: Apologies. It's taking longer than I thought to fix batch downloads.  Probably will not be ready until Tuesday (Sydney time).

Thanks.

**Comment by section83** [comment]
Release v1.23.1 should work properly. Had to muck around with a lot of code so, fingers crossed.

**Comment by kuglee** [comment]
Thanks.
