### ISSUE TITLE
Unable to extract Uploader ID

### ISSUE THREAD

**Issue by Tenz14** [section83/MacYTDL#64]
The downloads don't work now and instead we get the message saying "Unable to extract Uploader ID". Looked around to see if anyone else had this problem and saw that it was something to do with youtube implementing the @ channel name. Saw a lot of talk about it on the main ytdl but didn't see any here so just wanted to report it.

**Comment by section83** [comment]
I updated MacYTDL to deal with "Handle URLs" in version 1.23.  It works well as far as I can tell.

YT-DLP was updated to version 2023.02.17 which addressed a number of issues including with YouTube.  One of the fixes was:

    [extractor/youtube] Fix uploader_id extraction by [bashonly](https://github.com/bashonly)

>The downloads don't work now and instead we get the message saying "Unable to extract Uploader ID".

Can you describe a few things ?

- Which URLs are affected ?
- Is a log file saved ?
- Can you post a copy of this file: [Your Mac]/Users/[Your Home/Library/Preferences/MacYTDL/simulate.txt
- Can you post a capture of the error ?


Thanks.

**Comment by Tenz14** [comment]
All the URLs don't work. I even tried URLs that I have downloaded before and they seem to not work as well. 

Log
[youtube-dl_log-the-error-download-Monday_February_27_2023_at_1_50_17_AM.txt](https://github.com/section83/MacYTDL/files/10847006/youtube-dl_log-the-error-download-Monday_February_27_2023_at_1_50_17_AM.txt)

Screenshot
<img width="418" alt="Screen Shot 2023-02-28 at 12 43 51 AM" src="https://user-images.githubusercontent.com/98575655/221765700-4f351a3a-f78a-47ec-96ba-0b0a3f4c8112.png">

<img width="410" alt="Screen Shot 2023-02-28 at 12 44 16 AM" src="https://user-images.githubusercontent.com/98575655/221765715-9910cd7e-7832-4041-9bb8-f631cc865c7f.png">

**Comment by section83** [comment]
Both of those videos are no longer available:


<img width="1126" alt="Screenshot 2023-02-28 at 7 33 40 pm" src="https://user-images.githubusercontent.com/7471595/221798304-1c160314-81bb-4198-9ecf-00c6875b3da6.png">



Can you provide more example URLs ?

Also, please turn on "Verbose logging".  The resulting log file contains much more detail without which I can't diagnose the problem.

Thanks.

**Comment by Tenz14** [comment]
Sorry about that. Here is a more recent one.

[youtube-dl_log-the-error-download-Tuesday_February_28_2023_at_2_19_04_PM.txt](https://github.com/section83/MacYTDL/files/10853986/youtube-dl_log-the-error-download-Tuesday_February_28_2023_at_2_19_04_PM.txt)

**Comment by section83** [comment]
That video downloads normally:

<img width="281" alt="Screenshot 2023-03-01 at 10 10 54 am" src="https://user-images.githubusercontent.com/7471595/222003690-a88cdc9c-d319-4fa1-9e33-badab152b55f.png">

I think it would be best if you updated YT-DLP.  You are currently running version 2022.10.04.  There have been a lot of bug fixes since then including for the "Unable to extract Uploader ID" issue.

To update YT-DLP:

- Open MacYTDL.
- Click on "Utilities".
- Tick the box next to "Check for yt-dlp update".
- Click on "Start"
- Enter your admin credentials when asked.

Thanks.

**Comment by Tenz14** [comment]
When I try to update, I get the message that it's updated to the most recent one. 
<img width="420" alt="Screen Shot 2023-02-28 at 6 50 03 PM" src="https://user-images.githubusercontent.com/98575655/222009403-5ce47790-4ae1-4d86-96d1-a268cef3566d.png">

**Comment by Tenz14** [comment]
Follow up: The problem turns out to be my chrome version. It wasn't up to date so it was messing with MacYTDL. I updated the chrome browser to the latest version and now it works. Thanks a lot for all the replies.

**Comment by Tenz14** [comment]
Can you check if this video works? This one doesn't work.

[youtube-dl_log-the-error-download-Tuesday_February_28_2023_at_9_39_05_PM.txt](https://github.com/section83/MacYTDL/files/10856611/youtube-dl_log-the-error-download-Tuesday_February_28_2023_at_9_39_05_PM.txt)

**Comment by section83** [comment]
> When I try to update, I get the message that it's updated to the most recent one.

Sorry but, no.  That is the function for updating _MacYTDL_.  You need to update the _YT-DLP_ Python script which is used by _MacYTDL_ to download videos. Please follow the steps I suggested in my previous post.

> Can you check if this video works? This one doesn't work.

Sorry, but there is not enough detail in that file for me to work with.  Please turn on "**Verbose logging**":

- Open MacYTDL.
- Click on "Settings".
- Click on the tick box beside "Verbose logging".
- Click on "Save Settings".

Cheers.

**Comment by Tenz14** [comment]
Sorry, here is the verbose logging version.

[youtube-dl_log-the-error-download-Tuesday_February_28_2023_at_10_51_30_PM.txt](https://github.com/section83/MacYTDL/files/10856959/youtube-dl_log-the-error-download-Tuesday_February_28_2023_at_10_51_30_PM.txt)

**Comment by section83** [comment]
> Sorry, here is the verbose logging version.

Great, thanks.

That video downloads normally for me:

<img width="281" alt="Screenshot 2023-03-01 at 3 57 51 pm" src="https://user-images.githubusercontent.com/7471595/222048660-8a929c6f-4996-4c96-b7f6-862e1b33b5d6.png">

Please try to update YT-DLP:

- Open MacYTDL.
- Click on "Utilities".
- Click in the tick box next to "Check for yt-dlp update".
- Click on "Start"
- Enter your admin credentials when asked.

Cheers.

**Comment by Tenz14** [comment]
Okay. So, I updated it and now I'm getting a pop up like this. 

<img width="256" alt="Screen Shot 2023-03-01 at 2 30 16 AM" src="https://user-images.githubusercontent.com/98575655/222072805-4dbc12a6-bc67-45b3-982e-a5a5e51b3f57.png">

**Comment by section83** [comment]
Oh heck.  There is a bug somewhere.  It will be hard to find – I've just done another download of "Kelsang Shrestha - Tasbirma [Lyric Video]".  Worked perfectly.

Did you see either of these dialogs?

<img width="281" alt="Screenshot 2023-03-01 at 8 16 35 pm" src="https://user-images.githubusercontent.com/7471595/222096772-eb855516-25ea-4d8c-88a1-a349532d5fbb.png">
<img width="362" alt="Screenshot 2023-03-01 at 8 18 03 pm" src="https://user-images.githubusercontent.com/7471595/222096785-f508930f-40f7-4fe3-94b5-309e925393ba.png">

Currently, I suspect the bug is in code which shows the second dialog.  If you saw that dialog, then your download should have worked.

It will take me a some days to investigate further.  If you can't get any downloads to work with MacYTDL, and you can't wait, you could look for alternative downloaders.  I have found _[Downie](https://software.charliemonroe.net/downie/)_ to be good.

Many thanks for keeping in touch.

**Comment by section83** [comment]
Can you do me a favour and email a copy of this file:

>[Your Mac]/Users/[Your Home]/Library/Preferences/MacYTDL/MacYTDL.plist

My email address is in the "About" box accessible from the "Utilities" dialog.

Thanks.

**Comment by Tenz14** [comment]
Okay. I sent it.

**Comment by mmicha** [comment]
I have the same error
```
There was an error with the URL you entered:

'https://www.youtube.com/watch?v=dwYBkdi4_g4'

The error message was: 

WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = nUn6b7nf7t2I30pMhZ ; player = https://www.youtube.com/s/player/cfa9e7cb/player_ias.vflset/en_US/base.js
ERROR: [youtube] dwYBkdi4_g4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Quit, OK to return or Download to try anyway.
```
Error log
`[youtube] dwYBkdi4_g4: Downloading webpage
[youtube] dwYBkdi4_g4: Downloading android player API JSON
[youtube] dwYBkdi4_g4: Downloading player cfa9e7cb
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = ECEyDhdP8je6BbAaeS ; player = https://www.youtube.com/s/player/cfa9e7cb/player_ias.vflset/en_US/base.js
ERROR: [youtube] dwYBkdi4_g4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`

MacOS 12.6.5 (21G531)
MacYTDL 1.24.1

**Comment by section83** [comment]
[mmicha](https://github.com/mmicha), many thanks for posting.

This is a [problem with YT-DLP](https://github.com/yt-dlp/yt-dlp/issues/6953).  It seems to be intermittent.  I did a number of downloads from YT this morning with no trouble.  Please make sure you are using YT-DLP version 2023.03.04. Also, please turn on "Verbose logging" (in Settings). The detailed log file helps the YT-DLP developers.

If you get this warning dialog:

![Warning](https://github.com/section83/MacYTDL/assets/7471595/5e857e20-5f2a-4e42-a4a2-06e392246ee3)

Just click on "Download". So far it has worked for me.

You can try updating YT-DLP to the latest nightly build using Terminal:

`yt-dlp --update-to nightly`

There might be a fix in the nightly build (although, I can't find one at present).

I've found that just trying to download again often works.

**Comment by section83** [comment]
UPDATE: It looks like a fix for YT-DLP has been implemented for the warning on "nsig".  It is in the current nightly build.
