### ISSUE TITLE
Installation Issue: sh: /usr/local/bin/yt-dip: No such file or directory

### ISSUE THREAD

**Issue by PaperCloud10** [section83/MacYTDL#65]
![image](https://user-images.githubusercontent.com/71211547/232956167-5cddc443-8afd-41cc-9c53-d795e69859c1.png)

Hello, 

I am new to yt-dlp in general and have run into this issue during installation. Before I installed the GUI I already have yt-dlp installed  via Homebrew. I am on an M1 Macbook Air. If I create a folder named yt-dlp in the aforementioned directory then it throws this error:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/71211547/232956390-46aa7b40-a159-4b98-8dee-1f03b64a6392.png">

Any help would be appreciated!

**Comment by section83** [comment]
Thanks for making contact.  Sorry about the error.  There is no need to create a folder called "yt-dlp". MacYTDL installs yt-dlp into "/usr/local/bin" if there is no Homebrew/MacPorts install.

In version 1.24 I tried to pick up Homebrew installs if they preceded MacYTDL.  It was a bit tricky as Homebrew installs in different locations for ARM/Intel Macs.  On ARM Macs, it uses "/opt/hombrew/bin"/.

Can you help with a few questions ?

- Is there a file or alias/symlink called "yt-dlp" in  "/usr/local/bin" ?
  - If so, is it a file or symlink/alias ?
  - If a symlink/alias, where is the original stored ?
- Is there a file or alias/symlink called "yt-dlp" in  "/opt/homebrew/bin" ?
  - If so, is it a file or symlink/alias ?
  - If a symlink/alias, where is the original stored ?

If you have something called "yt-dlp" inside "/usr/local/bin", please delete it.  MacYTDL should then look for the Homebrew install.

If the Homebrew yt-dlp install worked, you should have a symlink in "/opt/hombrew/bin/.  As an experiment, can you delete that symlink (or just move it to the Desktop) and try MacYTDL again ?

Can you advise why you installed yt-dlp with Homebrew ?

Many thanks again.

**Comment by PaperCloud10** [comment]
Hello,

Unfortunately I cannot find the symlink/alias file in either /usr/local/bin or /opt/homebrew/bin, even after reinstalling yt-dlp using homebrew. There's no particular reason I installed using homebrew, it simply was the most convenient and yt-dlp has been working perfectly via terminal.

**Comment by section83** [comment]
> I cannot find the symlink/alias file in either /usr/local/bin or /opt/homebrew/bin

That's odd.  When I used Homebrew to install yt-dlp, a symlink was saved into /opt/homebrew/bin.  Can you have a look in /opt/Homebrew/Cellar.  It has to be somewhere.

Something to keep in mind with Homebrew is that it downloads, builds and installs all dependencies.  So, with yt-dlp, you also get a full Python install.  The yt-dlp_macos released on GitHub has everything built in.  Also, you have to manually update using Homebrew.  MacYTDL can check for and install updates to yt-dlp.

Thanks.

**Comment by section83** [comment]
I found the bug.  Forgot to tell MacYTDL that yt-dlp is to be called from /opt/homebrew/bin if Homebrew install is present. A fix will be in the next release.

Don't know why you can't find it.  I did an other clean Homebrew install of yt-dlp today and found a symlink in /opt/homebrew/bin and an executable in "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/bin/yt-dlp".

In the meantime, the only way for you to use MacYTDL is to remove the Homebrew install of yt-dlp. If that's inconvenient, you could look at other GUIs.  One that I can recommend is [Downie](https://software.charliemonroe.net/downie/). It has a complex set of preferences but is solid, highly functional and actively developed. I think it's the best video downloader I've seen.

Many thanks for raising the issue.
