### ISSUE TITLE
Got this after I let it access system events when trying to install.

### ISSUE THREAD

**Issue by JAKHIGDON** [section83/MacYTDL#68]
<img width="259" alt="Screenshot 2023-07-18 at 11 15 46 AM" src="https://github.com/section83/MacYTDL/assets/88561983/921e8992-8e7f-48fe-aabc-2b6f715e07dc">

Not sure what's up. It's my work computer (Im a creative so having this is no issue) but I don't have ready access to terminal or changing anything serious without getting IT to hover over me and type in the admin password everytime.

**Comment by section83** [comment]
[JAKHIGDON](https://github.com/JAKHIGDON), many thanks for posting.

I've seen that error when MacYTDL is run from within the DMG file.  By any chance did you try to run MacYTDL from within the DMG file ?  If so, click and drag MacYTDL out to your Desktop or into the /Applications/ folder and try again.

The DMG doesn't contain an "installer".  It only contains the MacYTDL applet, help and release notes.  MacYTDL does install a number of files when first run but, it can't be run reliably from within the DMG file.

Thanks.
