### ISSUE TITLE
all files output as 'filename'.mp4

### ISSUE THREAD

**Issue by williamcorney** [section83/MacYTDL#69]
I want to download in batch a load of files which are all come from a m3u8 file called master.m3u8. 

The issue I'm having is that the m3u8 file doesn't contain any unique info such as episode number and so the files all download as master.mp4

Unless I manually move each file as it downloads, the next download in batch fails as there exists already a master.mp4 in the output location

I have tried editing the batch text file and changing name or adding the name to the custom output  file but it seems to always default to the name of the m3u8 file

many thanks

**Comment by williamcorney** [comment]
This can be closed 

The issue was caused because I hadn't ticked the custom name box.  I had assumed that putting text in the box alone activated the option

**Comment by section83** [comment]
> I had assumed that putting text in the box alone activated the option

Yes, sorry, it's a very basic applet.  Thanks for reporting anyway.
