### ISSUE TITLE
/usr/local/opt/libunistring/lib/libunistring.2.dylib not loaded

### ISSUE THREAD

**Issue by macmeister1967** [section83/MacYTDL#70]
dyld: Library not loaded: /usr/local/opt/libunistring/lib/libunistring.2.dylib
  Referenced from: /usr/local/opt/gnutls/lib/libgnutls.30.dylib
  Reason: image not found
sh: line 1: 11056 Abort trap: 6           ffmpeg -version (134)

This is on first launch, then the app closes :(

Any ideas?

Using macOS Mojave 10.14.6

**Comment by macmeister1967** [comment]
I am attempting to install gnutls via brew... but using Mojave, brew is a coin-toss at best.

**Comment by section83** [comment]
I've not seen any of these errors before.  MacYTDL does recognise a Homebrew install of FFmpeg but, I've not done a lot of testing.

>I am attempting to install gnutls via brew

MacYTDL does not need gnutils.

Can you provide some more detail ?

* Have you run MacYTDL before ?
* Do you need to install FFmpeg via Homebrew ? [MacYTDL can install the latest version directly]
* Have you installed FFmpeg via Homebrew in the past ?  If so, is it up-to-date ?

Thanks.

**Comment by macmeister1967** [comment]
I installed gnutls using Port, and then symlinked the much newer libs,
seems to work fine now... except with DRM content - haha

**Comment by section83** [comment]
OK.  Let me know if you have problems with MacYTDL.

Cheers.

**Comment by macmeister1967** [comment]
It crashed once while trying to force a DRM protected video... but it has been rock-solid downloading supported files... many thanks for a great program/frontend.

**Comment by macmeister1967** [comment]
NOTE: I did not have the required libunistring folder until I installed gnutls with Ports

**Comment by section83** [comment]
>It crashed once while trying to force a DRM protected video

Shouldn't crash if a video is DRM'd. MacYTDL should show this dialog:

![DRM](https://github.com/section83/MacYTDL/assets/7471595/9c5fe082-7580-4d91-8f03-264df8f2a3ba)

> I did not have the required libunistring folder until I installed gnutls with Port

Thanks but, I don't use gnutls etc.  I have used Homebrew and MacPorts only so MacYTDL can recognise installs by those tools.

Cheers.

**Comment by macmeister1967** [comment]
OK, I started another issue re:subtitles missed in batch mode.
