### ISSUE TITLE
Missing vtt subtitles in batch mode

### ISSUE THREAD

**Issue by macmeister1967** [section83/MacYTDL#71]
I recently tried to get about 9 episodes of two series which contain VTT subtitles. I had preferences set to "Best" for subtitles, and it downloaded the first one, but no more. I then tried them one at a time with preferences set to VTT and they all downloaded correctly.

This was ABC iView in Australia :-)

**Comment by section83** [comment]
Can you provide the iView URL ?  So far, it's working for me but, it might depend on the particular iView show.

**Comment by macmeister1967** [comment]
Sadly, that file is now empty... try a batch from two seasons on
SUBTITLE=BEST, see if the 2nd and 3rd subtitles download (that was my
issue... normally the VTT files downloads BEFORE the video/audio, so it was
noticeable when that didn't happen!

**Comment by section83** [comment]
Yes, sorry.  It was a "successful" download so, the batch list was cleared.

The code which does a batch download ignores the subtitles setting.  I've fixed that and it will be in release 1.26 (or 1.25.1 if that happens).

Cheers.

**Comment by macmeister1967** [comment]
Many thanks... the subtitles are a must for me. Hate how 7+ doesn't seem to
have a single subtitle, or an option in the player to even ENABLE subtitles
:-(

**Comment by section83** [comment]
>7+ doesn't seem to have a single subtitle, or an option in the player to even ENABLE subtitles

I think it varies with the show.  Some don't have closed captions while others do.  For example there is a closed captions logo in the top RH corner for this show:

![Screenshot 2023-11-02 at 11 46 32 am](https://github.com/section83/MacYTDL/assets/7471595/42c7fcfb-6c23-4acf-bcb3-c942ee8dd34c)

**Comment by macmeister1967** [comment]
DAyum!

I need to keep a whether eye out for that. I was looking at downloading
Bargain Hunt, and it does not seem to be subtitled at all, occasionally we
spot it on another channel, and it DOES have subtitles, so I guess it is
what that channel is prepared to pay, or what time it is shown? (I know
there is a self-policing policy of 6pm - 10pm requiring subtitles for the
deaf/hard of hearing).

Still, great news about CC on 7

**Comment by macmeister1967** [comment]
PS. I use https://www.happyscribe.com/subtitle-tools/subtitle-converter/

to convert my VTT to SRT.

I don't know if they have an API at all, but that would be a neat feature
in your frontend - if you could automate the conversion, seeing 99% of what
I have found is VTT subtitles?!

Cheers!

**Comment by section83** [comment]
>, seeing 99% of what I have found is VTT subtitles?!

Yes, VTT is common. 

> if you could automate the conversion,

Usually, if you set "Subtitles format" to "srt" or something you want, MacYTDL will download what's available and convert it to what you want.  However, there is a problem with "webvtt" which is the format used by iView.  I need to do more research on why it's not working.

Thanks.
