### ISSUE TITLE
Choose Formats  exceeds screen boundaries

### ISSUE THREAD

**Issue by CharlesLai0307** [section83/MacYTDL#72]
version: 1.25 . 8 September 2023
When "Choose Formats" is displayed, the list is too long and exceeds the screen boundaries.

**Comment by section83** [comment]
Thank you for posting this.  Yes, the dialog is too long especially when listing formats provided by YouTube.  I use MacYTDL on a 720p TV and the dialog really is tooo long.

I'll work on redesigning the dialog. One option is to make the dialog double width.  But extra wide dialogs can be problematic too. Another option would be to only show formats consistent with the "Remux_format" and/or "File format" settings.  Unfortunately, I don't think there's a way to show the formats list in a scrollable pane (using _AppleScript_ and the current _Dialog Toolkit_).  It might take a while to solve this problem.

In the meantime, pressing command–. (ie command and full stop) will cancel the dialog. I would suggest just pressing Return to continue the download with defaults but there is a fatal bug in that code.

I'll post here if I find a solution.

**Comment by section83** [comment]
I have a new "Choose Formats" dialog. Decided to use another script library which provides scrollable tables. Also, the dialog can be resized.  Result is different layout to other dialogs but not too bad. Have decided to go with this for the next release of MacYTDL.

![New dialog](https://github.com/section83/MacYTDL/assets/7471595/2f30e5c1-c376-4218-9415-b75d8d9ae919)
