### ISSUE TITLE
Can a schedule timer (start/stop) be added?

### ISSUE THREAD

**Issue by palomnik** [section83/MacYTDL#74]
I love MacYTDL!  The one thing that would make it perfect is the ability to schedule a download with start and stop time, to record live videos at various times. Can this be added as a feature request? TIA.

**Comment by section83** [comment]
Hello palomnik !  Thank you for the suggestion. A friend made the same suggestion a few years ago.  I've not done it yet because I have been worried about the complexities. But I'll have another look at what would be needed.

Cheers.
