### ISSUE TITLE
error when trying to download https://youtu.be/U5PRXTskyJo?list=PLutAIE63uaHwsO7Fosq3WLGGLtCgeuOpO

### ISSUE THREAD

**Issue by ComfortableMilk4454** [section83/MacYTDL#77]
<img width="532" alt="image" src="https://github.com/section83/MacYTDL/assets/43555540/453e9d60-cc4d-4fa9-98e5-8b7690bd77da">

**Comment by section83** [comment]
Thanks for making contact.

Yes, YouTube has been banging those warnings for a few months.  They seem to be related to a redirection that happens with some videos that are preceded by an advertisement. The downloads always work.

The next version of MacYTDL will have a setting to suppress all those warnings.  It's not something I can fix in MacYTDL – it requires a change in yt-dlp.

Cheers.

**Comment by ComfortableMilk4454** [comment]
got it. thanks so much for the info and super fast response! i will hit the continue button :))
