### ISSUE TITLE
List of other proposed improvements

### ISSUE THREAD

**Issue by section83** [section83/MacYTDL#9]
1.	Look at whether “--merge-output-format” is a useful option to add.
	*	Only if merging video and audio files.
2.	Add settings for Adobe Pass credentials, video password and .netrc credentials.
3.	Add settings for “--autonumber-start” and “--output-na-placeholder”.
4.	Redesign Settings dialog – e.g. group settings types. 
5.	Consider whether/how to initiate parallel downloads when user pastes multiple URLs. 
	*	Currently downloads serially by one YTDL request. Could go parallel.
6.	Enable user to save one or more set of login credentials – could use KeyChain.
7.	Enable user to keep original file(s) when downloads are automatically merged (usually by FFmpeg). 
8.	Option to add ad-hoc arguments to ytdl command.
	*	Or, perhaps, better to use a config file.
9.	Option on installation to add shortcut to Dock.
	*	Involves killing the Dock process (which usually restarts) so that change to a plist file is implemented.
10.	Organising downloads by uploader/downloader
	*	Is this of any benefit ?
12.	Add facility for user to choose file format(s) for audio and video from range available.
13.	Add option to control downloads according to date ?
14.	Option to schedule downloads for a later time ?
15.	Add YTDL "Archives" functionality.
16.	Enable finer choices on codecs ?
17.	Add option to auto-download when invoking Service.
18.	Redisplay the "Monitor" dialog after user clicks on "Logs" button (rather than closing the dialog).
19.	Enable the Monitor dialog to be hidden/minimised and non-modal – very difficult using AppleScript.
20.	Enable user to position the Monitor dialog – tricky as each dialog is a separate process.
 	*	Might be possible to keep separate processes but one dialog.
21.	Add file count to Monitor dialog for multiple downloads e.g. playlists.
22.	Add option to choose playlist items for download – currently always download entire list.
23.	Add option to delete URLs from batch file after download.
24.	Add option to choose downloads from batch file – currently always downloads entire batch.
25.	Add option to store YTDL settings with each URL in a batch – would enable different settings for each download.

**Comment by SwineBurglar** [comment]
Bumping for #14! I just found this GUI for youtube-dl. It's wonderful for getting the job done more easily but I am still using youtube-dl in the command line for anything that I want to keep the automatic subtitles for, if it doesn't have English subs I can grab via MacYTDL.

**Comment by section83** [comment]
OK, I'll look at #14 for v1.16.  After spending so much time bug hunting, it will be good to add something new. Many thanks.

**Comment by SwineBurglar** [comment]
Wow! Thank you. That would be great.

**Comment by section83** [comment]
Starting my research on #14.  I know very little about YouTube's auto generated subtitles.  Do you think it should be a separate option ?  Does it apply only to Youtube ?

**Comment by SwineBurglar** [comment]
I'm not super knowledgeable about the auto-generated subtitles, either, but I do think it should be a separate option in MacYTDL. My reasoning is that it is possible for a given YouTube video to have both author-generated subtitles and auto-generated subtitles, so you might as well make the auto-generated subtitle download a separate option that is not affected by the presence of author-generated subtitles. A lot of times, when I'm grabbing some random video with youtube-dl, I don't actually check if it has author-generated subtitles. I just have my flags set in my config file to `--write-sub --sub-lang en --write-auto-sub" so it will grab the auto-generated subs in English and if there are author-generated subs, it will also grab those. Since subtitle files are so relatively small, it doesn't hurt anything to grab both.

I haven't ever seen auto-generated subtitles on any other similar sites to YouTube, so I'm not sure if it's exclusive to YouTube, but I would venture to guess YouTube's implementation of that feature is not something standard, so even if other websites have auto-generated subs available, youtube-dl might not be able to interact with them properly. I've run into that issue with the output template options on other websites where youtube-dl couldn't grab the upload date or author name. It seems that youtube-dl is mainly intended for use on YouTube and the support for other sites is more bare-bones.

**Comment by section83** [comment]
Yes, I think it'll be best to keep _--write-auto-sub_ a separate option.  By the way, when I've tested requesting both kinds of subtitles, YTDL has failed to report the auto-generated subs are available.  I've asked the question: [https://github.com/ytdl-org/youtube-dl/issues/27306](https://github.com/ytdl-org/youtube-dl/issues/27306).  No answers as yet.

Some people have found _--write-auto-sub_ works on Vimeo even though the YTDL readme says "YouTube only".  Anyway, If I have time, I'll put in a warning if the user requests auto generated subs from other than YouTube.  That way, they will know it might not work.

Thanks.

**Comment by section83** [comment]
It's a bug which has been reported: https://github.com/ytdl-org/youtube-dl/issues/27315.  I've added the option to Settings but that's all.  I can't test any code until the YTDL developers fix the bug.

**Comment by martinsstuff** [comment]
MacYTDL really needs re-encoding options, applications with limited playback support (i.e. not VLC or ffmpeg based apps) can't work with certain videos downloaded from YouTube, even if they are remuxed.

Fortunately youtube-dl comes with the options `--extract-audio` & `--audio-format FORMAT` (for audio) and `--recode-video FORMAT` (for video) which, though taking a bit (progress indicator?) do the job and ensure video can be played in QuickTime and embedded in, for instance, PowerPoint.

**Comment by section83** [comment]
Hmmm. Yes, the "remux" setting in MacYTDL does do a --recode-video.  Remuxing is done by FFmpeg controlled by youtube-dl. The result can depend on the source file and the format is requested.  MacYTDL allows all formats provided by youtube-dl [mp4, mkv, webm, ogg, avi, flv, aac, flac, mp3, m4a, opus, vorbis, wav].  There is also an "audio only" setting.

Now that I look at them, it's odd having the audio formats in the "remux" settings. It does work but needs more thought to make it understandable.  The Help file is a tad obtuse on this.  If you specify download format as mp4 and then remux to mp3, MacYTDL will automatically add the options needed to convert audio to the desired format.  The YTDL command will be like this:

> youtube-dl --ignore-errors --newline -f 'bestvideo[ext=mp4]+bestaudio/best[ext=mp4]/best' --extract-audio --audio-format 'mp3' --audio-quality 0 --no-overwrites --verbose -o '%(title)s.%(ext)s' [URL]

But, currently, MacYTDL can't recode both the audio to, e.g., mp3 and the video to e.g., mp4.  In fact it will delete the original download if "keep original" is not set.  So, I need to rethink how those settings work.

In your testing make sure you have the "verbose" setting on.  The resulting output is crucial for diagnosing issues.  Can you [send me details of the video you had problems with](mailto:macytdl@gmail.com) ?  At least the URL so I can go through what might have happened.

**Comment by section83** [comment]
In v1.16, I have worked on the audio-only and remuxing options.  It should be better now.  Can now choose the audio format directly and can remux the container of an audio-only download (although, I doubt it will be very useful).

**Comment by section83** [comment]
Closing this to clean up. Better list of proposed changes in a new issue.
